name: cats_my_facts
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^3.0.1+1
  hive: ^2.2.3
  bloc: ^8.1.0
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  sizer: ^2.0.15
  google_fonts: ^3.0.1
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  animate_do: ^2.1.0

dev_dependencies:
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: ^2.2.0
  json_serializable: '>4.4.0'
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - loading.gif
    - error.gif

  